# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               jzieg
tagline:             'a jekyll blog'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://jzieg.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Joachim Ziegemann
  url:               https://twitter.com/jziegemann
  email:             jziegemann@gmail.com

# Custom vars
version:             1.0.0
